version: '3'
services:
  production: &prod
    build:
      context: .
  dev: &dev
    <<: *prod
    image: keboola/php-storage-driver-bigquery
    volumes:
      - ./:/code
  dev-xdebug:
    <<: *dev
    build: etc/docker/xdebug
