version: '3'
services:
  production: &prod
    build:
      context: .
    environment:
        - BQ_PRINCIPAL
        - BQ_FOLDER_ID
        - BQ_SECRET
        - BQ_STACK_PREFIX
        - BQ_BUCKET_NAME
        - BQ_KEY_FILE
        - BUILD_ID
  dev: &dev
    <<: *prod
    image: keboola/php-storage-driver-bigquery
    volumes:
      - ./:/code
  dev-xdebug:
    <<: *dev
    build: etc/docker/xdebug
