name: Tests
concurrency: tests # ensure that test are not running in same time

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Build Image
        run: docker-compose build

      - name: Run Tests
        env:
          BQ_PRINCIPAL: ${{ secrets.BQ_PRINCIPAL }}
          BQ_PRIVATE_KEY: ${{ secrets.BQ_PRIVATE_KEY }}
          BQ_FOLDER_ID: ${{ secrets.BQ_FOLDER_ID }}
        run: docker-compose run --rm production composer ci
